name: Docker Image CI
on:
  push:
    branches: ['master']
env:
  TAG: ${{ secrets.DOCKER_HUB_REPO }}:latest
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
        APP_KEYS: ${{ secrets.APP_KEYS }}
        DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
        DATABASE_FILENAME: ${{ secrets.DATABASE_FILENAME }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker image & push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.TAG }}
          cache-to: type=inline